Ios tc0001
whetman/carina-native-app pull request #5
Opened 2024-07-23 10:44 UTC by whetman

This pr consist two tests, one validating logging - this feature doesn't work on the app I am testing since the keyboard opening on the app is not working properly (we talked about it on one of the meetings). 
I decided to leave this test anyway, halfway done.

2024-07-31 09:13 UTC, MariuszSolvd commented
I check TC1, TC2 and TC3, I assume all TC works same. It doesn't kill app after test is done, so you can't run more than one without manually closing app by yourself.

2024-07-31 09:18 UTC, MariuszSolvd commented
I see that you use in classes over and over again `setPageOpeningStrategy(PageOpeningStrategy.BY_ELEMENT);` you can just use it once in config so no need to repeat it each time in classes. Example of how to set it `page_opening_strategy=BY_ELEMENT` <--- Strategy
`element_loading_strategy=BY_VISIBILITY` <---- Condition

2024-07-31 09:34 UTC, MariuszSolvd commented
I would say #TC0001 is pointless. You can't login to the app by typing username and password. Even if you would find a way to close keyboard, still it seems that Login button does not work after taping on input fields. So I would either just delete this TC or click on hardcoded user, and login this way.

2024-07-31 09:37 UTC, MariuszSolvd commented
In `LoginPageBase` you don't need to use `this` keyword in constructor, since you do not have any other variable called `loginButton`

2024-07-31 09:52 UTC, MariuszSolvd commented
Any reason why you make SortingBase class and then Sorting class extends it? Why not make just Sorting since you don't have more than one inheritor? Do you plan to have more than one?

2024-07-31 10:27 UTC, MariuszSolvd commented
In ```CatalogPageBase``` there is a Sorting field. I don't understand why you use this locator`**/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]` I check it in Appium Inspector and it seems like it's Products page element not sorting pop-up window, which would be ```**/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther``` or smaller Class Chain ```**/XCUIElementTypeOther[$type == 'XCUIElementTypeButton' AND name == 'Name - Ascending'$][-1]```

2024-07-31 10:36 UTC, MariuszSolvd commented
In ```SortingBase``` you have field ```private List<Product> products```.  ```Sorting``` class you use in only in ```CatalogPageBase``` where you already has field ```private List<Product> products```, so you are repeating same field, just one is nested in ```Sorting```, why?

2024-07-31 10:48 UTC, MariuszSolvd commented
In ```CartPageBase``` you use keyword ```this``` in constructor when you have just one ```cartScreen``` variable. I just go trought few classes and you do it in them as well. From my understanding of Java you don't need you use ```this``` when there is just one variable of this name inside class, it's redundant. You should use ```this``` when you have same named variable for an example you would inject some ExtendedWebElement inside constructor and called it cartScreen then you need to specify which one belongs to the class.

2024-07-31 10:59 UTC, MariuszSolvd commented
#TC0003 I would make 2 separated TC since it check functionality on two separate pages product and cart. I imagine it would be good to run for an example TC with product and get assertion, and TC with cart one and get assertion as well. This way if you would maintain let's say 400 test, it would be easier, since you would have it separated, and instantly know if it's product page or cart page.

2024-08-05 08:16 UTC, whetman commented
> I check TC1, TC2 and TC3, I assume all TC works same. It doesn't kill app after test is done, so you can't run more than one without manually closing app by yourself.

Yes, you are right, I will add it after I finish all the TC, so I will leave this open

2024-08-05 08:21 UTC, whetman commented
> I would say #TC0001 is pointless. You can't login to the app by typing username and password. Even if you would find a way to close keyboard, still it seems that Login button does not work after taping on input fields. So I would either just delete this TC or click on hardcoded user, and login this way.

I didn't notice that there was an option like this, that's the only reason I left it like this 😅 I will change it, thanks!

2024-08-05 08:24 UTC, whetman commented
> Any reason why you make `SortingBase` class and then `Sorting` class extends it? Why not make just Sorting since you don't have more than one inheritor? Do you plan to have more than one?

I was thinking that it may be different for Android, but I don't know it at the moment

2024-08-05 08:26 UTC, whetman commented
> In `CatalogPageBase` there is a Sorting field. I don't understand why you use this locator`**/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]` I check it in Appium Inspector and it seems like it's Products page element not sorting pop-up window, which would be `**/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther` or smaller Class Chain `**/XCUIElementTypeOther[$type == 'XCUIElementTypeButton' AND name == 'Name - Ascending'$][-1]`

I am not sure at the moment, but if I remember correctly I had to change this locators for longer ones, because for some reason this nice ones didn't work and were unclickable, but I will check it again

2024-08-05 08:29 UTC, whetman commented
> In `SortingBase` you have field `private List<Product> products`. `Sorting` class you use in only in `CatalogPageBase` where you already has field `private List<Product> products`, so you are repeating same field, just one is nested in `Sorting`, why?

I probably left a wip here, so I will change it

2024-08-05 08:30 UTC, whetman commented
> #TC0003 I would make 2 separated TC since it check functionality on two separate pages product and cart. I imagine it would be good to run for an example TC with product and get assertion, and TC with cart one and get assertion as well. This way if you would maintain let's say 400 test, it would be easier, since you would have it separated, and instantly know if it's product page or cart page.

Yes, I guess I can separate them

2024-08-05 08:34 UTC, MariuszSolvd commented
> > Any reason why you make `SortingBase` class and then `Sorting` class extends it? Why not make just Sorting since you don't have more than one inheritor? Do you plan to have more than one?
> 
> I was thinking that it may be different for Android, but I don't know it at the moment

Ok if you plan to make Android testing for MyDemoApp, it isn't bad approach, just one thing, you need to move abstraction to ```fooPageBase``` and then implementation to ```fooPage```.

2024-08-05 08:37 UTC, whetman commented
> > > Any reason why you make `SortingBase` class and then `Sorting` class extends it? Why not make just Sorting since you don't have more than one inheritor? Do you plan to have more than one?
> > 
> > 
> > I was thinking that it may be different for Android, but I don't know it at the moment
> 
> Ok if you plan to make Android testing for MyDemoApp, it isn't bad approach, just one thing, you need to move abstraction to `fooPageBase` and then implementation to `fooPage`.

Why to move it to fooPageBase? It's a component not a page, or do I misunderstood something?

2024-08-05 08:48 UTC, MariuszSolvd commented
> > > > Any reason why you make `SortingBase` class and then `Sorting` class extends it? Why not make just Sorting since you don't have more than one inheritor? Do you plan to have more than one?
> > > 
> > > 
> > > I was thinking that it may be different for Android, but I don't know it at the moment
> > 
> > 
> > Ok if you plan to make Android testing for MyDemoApp, it isn't bad approach, just one thing, you need to move abstraction to `fooPageBase` and then implementation to `fooPage`.
> 
> Why to move it to fooPageBase? It's a component not a page, or do I misunderstood something?

Let me explain on an example. ```CatalogBasePage``` it's an abstract class so there should be an abstraction, and in your case, you have there whole implementation. Then in ```ios``` package you have ```CatalogPage``` which should be implementation of the abstract class, but it not. So what you should do, with every ```FooBasePage``` it's to move an abstraction there, and then implement it in classes like ```FooPage```. Otherwise abstraction is redundant 'cuz you already know what you want to implement in abstraction.

2024-08-05 12:10 UTC, whetman commented on src/main/java/com/solvd/demoapp/pages/common/ProductPageBase.java
> +        Boolean isBlackAvailable = color.getColorBlack().isVisible(0);
Done!

2024-08-05 12:14 UTC, AnnaSolvd commented on src/main/java/com/solvd/demoapp/pages/common/LoginPageBase.java
> +    @ExtendedFindBy(iosClassChain = "**/XCUIElementTypeStaticText[`name == \"bob@example.com\"`]")
Is there a more general way for getting the locator? You can locate the element by referring to parent

2024-08-05 15:31 UTC, whetman commented
> > I check TC1, TC2 and TC3, I assume all TC works same. It doesn't kill app after test is done, so you can't run more than one without manually closing app by yourself.
> 
> Yes, you are right, I will add it after I finish all the TC, so I will leave this open

Done

2024-08-05 15:36 UTC, whetman commented on src/main/java/com/solvd/demoapp/pages/common/LoginPageBase.java
> +    @ExtendedFindBy(iosClassChain = "**/XCUIElementTypeStaticText[`name == \"bob@example.com\"`]")
Done

2024-08-05 15:56 UTC, AnnaSolvd commented on src/main/java/com/solvd/demoapp/pages/common/CatalogPageBase.java
> +        Random rand = new Random();
This line of code is duplicated is 3 methods:
```
Random rand = new Random();
int index = rand.nextInt(products.size());
```
You can create seperate method for this:
```
private int getRandomProductIndex() {
        Random rand = new Random();
        int index = rand.nextInt(products.size());
        LOGGER.info("Selected random product index: " + index);
        return index;
    }
```

2024-08-06 08:19 UTC, MariuszSolvd requested changes

2024-08-06 08:19 UTC, MariuszSolvd commented on src/main/java/com/solvd/demoapp/pages/common/LoginPageBase.java
> +    @ExtendedFindBy(iosClassChain = "**/XCUIElementTypeButton/XCUIElementTypeStaticText[2]")
I think this locator would better **/XCUIElementTypeButton[`name == "bob@example.com"`] it takes whole element, and it's more readable, I just see name, and I know where to look for it, even tho I didn't test this app.

2024-08-06 08:24 UTC, MariuszSolvd approved these changes

2024-08-06 08:24 UTC, MariuszSolvd commented on src/test/java/com/solvd/tests/AbstractTest.java
> +        catalogPage.terminateApp(R.CONFIG.get("capabilities.bundleId"));
I see that you implement terminate app after each test, well done!

2024-08-06 08:34 UTC, whetman commented on src/main/java/com/solvd/demoapp/pages/common/CatalogPageBase.java
> +        Random rand = new Random();
Yes, you are right! I also use it in some other methods in other classes so I will create util class for it with static method

2024-08-06 08:42 UTC, MariuszSolvd approved these changes
I can see that you changed Sorting class, and have new approach to check sorting, and don't have nested List<Product> I like it! I also can see that you implemented all suggestion I gave you, good job!
Keep in mind tho, that if you will want to add Android, cuz of implementation in abstract classes it would take you more time, as we discussed in call yesterday. I understand that you want to implement just iOS so leave this way. In this case it's ok.

2024-08-06 08:42 UTC, MariuszSolvd commented on src/main/java/com/solvd/demoapp/pages/common/CatalogPageBase.java
> +    @ExtendedFindBy(iosClassChain = "**/XCUIElementTypeOther[$type == 'XCUIElementTypeButton' AND name == 'Name - Ascending'$][-1]")
Fixed locator, I like it! :)

2024-08-06 08:42 UTC, MariuszSolvd commented on src/test/java/com/solvd/tests/demoapp/MyDemoAppTest.java
> +        int descending = firstProductDesc.compareTo(lastProductDesc);
If I understand well what are you tring to do here, I would use equals since it returns boolean. I think you could even use it already in assertion like assertEquals() or assertNotEquals

2024-08-06 09:00 UTC, AnnaSolvd approved these changes

2024-08-06 09:51 UTC, merged